### ISSUE TITLE
TypeError in central_system.py: on_connect() missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by jihun212** [EVerest/ocpp-csms#3]
![깃이슈질문글](https://github.com/user-attachments/assets/b3b63d81-9e3f-472b-84f5-71b5766a208a)

https://everest.github.io/nightly/tutorials/how_to_plug_and_charge/index.html

While following the tutorial Plug and Charge, I encountered the following issue when running central_system.py as part of the OCPP CSMS setup

Is there a known issue with the central_system.py script or additional configuration required to fix this?

Error Log:
`INFO:websockets.server:server listening on 0.0.0.0:9000
INFO:root:OCPP CSMS Started listening to new connections...
INFO:websockets.server:connection open
ERROR:websockets.server:connection handler failed
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/asyncio/server.py", line 373, in conn_handler
    await self.handler(connection)
TypeError: on_connect() missing 1 required positional argument: 'path'
`

**Comment by relaxkimo** [comment]
I've encountered this too, you can lower the websockets version to 13 and it will work.

**Comment by jihun212** [comment]
> I've encountered this too, you can lower the websockets version to 13 and it will work.

Thank you for your support, the issue is resolved!
